---
name: Lint

on:
  push:
  pull_request:

permissions: read-all

jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter on new changes
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DISABLE_ERRORS: false
          SHFMT_ARGUMENTS: "-i 4"
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_GITHUB_ACTIONS: true